#!/usr/bin/env python3
"""Build native fire-sorcerer sprites from the accepted imagegen sources.

The raw imagegen files are intentionally retained under
``dev_assets/source_images/fire_sorcerer``.  This pipeline removes their
connected green screen, validates every source cell with
``pixel_grid_analyzer.analyze_image``, and only then samples the detected
logical grid.  The legacy four-frame move row remains in the 4x4 atlas for
source continuity. Runtime movement is authored separately as an eight-pose
4x2 imagegen sheet, built into a 320x40 strip, and registered to the same
center/ground contract as the Frost Sorcerer walk.

Output contracts:

* fire_sorcerer.png: 4x4 cells, exactly 40x40 pixels per cell.
* fire_sorcerer_move.png: 8x1 cells, exactly 40x40 pixels per cell.
* fire_sorcerer_fireball.png: 4x4 cells, exactly 32x32 pixels per cell.
* all output alpha values are binary (0 or 255).
* character frames share one last-visible-pixel foot baseline.
* every AtlasTexture generated by this script is at most 40x40 pixels.
"""

from __future__ import annotations

from collections import OrderedDict
import hashlib
from pathlib import Path
from statistics import median

import numpy as np
from PIL import Image

from pixel_grid_analyzer import analyze_image
from process_frost_sorcerer_assets import (
    MOVE_FRAME_COUNT,
    _assert_move_strip_contract,
    _build_move_strip,
)


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "dev_assets/source_images/fire_sorcerer"
TEXTURE_DIR = ROOT / "resources/texture"
ANIMATION_DIR = ROOT / "resources/animation"

CHARACTER_SOURCE = SOURCE_DIR / "fire_sorcerer_generated_v2.png"
CHARACTER_REPLACEMENT_SOURCE = (
    SOURCE_DIR / "fire_sorcerer_attack_1_generated_v1.png"
)
FIREBALL_SOURCE = SOURCE_DIR / "fire_sorcerer_fireball_generated_v1.png"
CHARACTER_MOVE_NATIVE_SOURCE = (
    SOURCE_DIR / "fire_sorcerer_move_native_v1.png"
)
CHARACTER_MOVE_SOURCE = SOURCE_DIR / "fire_sorcerer_move_8pose_alpha.png"

CHARACTER_OUTPUT = TEXTURE_DIR / "fire_sorcerer.png"
CHARACTER_MOVE_OUTPUT = TEXTURE_DIR / "fire_sorcerer_move.png"
FIREBALL_OUTPUT = TEXTURE_DIR / "fire_sorcerer_fireball.png"
CHARACTER_ANIMATION_OUTPUT = ANIMATION_DIR / "fire_sorcerer.tres"
FIREBALL_ANIMATION_OUTPUT = ANIMATION_DIR / "fire_sorcerer_fireball.tres"
CHARACTER_ANIMATION_UID = "uid://fq4hw782ls7f"
CHARACTER_TEXTURE_UID = "uid://n2vio6cf7374"
FIREBALL_ANIMATION_UID = "uid://clyqfauajs7ku"
FIREBALL_TEXTURE_UID = "uid://dfpioy7k740tx"

GRID_COLUMNS = 4
GRID_ROWS = 4
CHARACTER_FRAME_SIZE = 40
FIREBALL_FRAME_SIZE = 32
MAX_LOGICAL_SUBJECT_SIZE = 40
MIN_GRID_CONFIDENCE = 0.65
CHROMA_TOLERANCE = 72
CHARACTER_REPLACEMENT_CELL = (2, 1)
OPTIONAL_EMPTY_CHARACTER_CELL = (3, 3)
OPTIONAL_EMPTY_FIREBALL_CELL = (3, 3)
CHARACTER_FOOT_BASELINE_Y = 38
CHARACTER_WAIST_ROWS = (22, 23)
CHARACTER_MOVE_TARGET_HEIGHTS = (29, 28, 29, 30, 30, 28, 29, 30)
STATIC_CHARACTER_ROWS_RGBA_SHA256 = (
    "aae16cb9b2c06bf23af3737668fa59476aff1392fde46cfbd5b8c4b1e435c75a"
)
CHARACTER_MOVE_RGBA_SHA256 = (
    "4ca274bcfdaedb1c0b26418d131cc850401fdd61fee8c5b611a6c51ca7069c21"
)
CHARACTER_MOVE_8POSE_RGBA_SHA256 = (
    "ddf3cf3acec35e60f14c0393a8209bd3d257147f95f801f3264afafc2f20900b"
)

CHARACTER_ANIMATIONS = OrderedDict(
    [
        ("move", (0, 12.0, True)),
        ("windup", (1, 6.0, False)),
        ("attack", (2, 8.0, False)),
        ("death", (3, 7.0, False)),
    ]
)
FIREBALL_ANIMATIONS = OrderedDict(
    [
        ("fly", (0, 12.0, True)),
        ("spawn", (1, 8.0, False)),
        ("impact", (2, 12.0, False)),
        ("expire", (3, 12.0, False)),
    ]
)


class AssetContractError(RuntimeError):
    """Raised when an imagegen source fails a non-negotiable pixel contract."""


def _require_sources() -> None:
    missing = [
        source
        for source in (
            CHARACTER_SOURCE,
            CHARACTER_REPLACEMENT_SOURCE,
            FIREBALL_SOURCE,
            CHARACTER_MOVE_NATIVE_SOURCE,
            CHARACTER_MOVE_SOURCE,
        )
        if not source.is_file()
    ]
    if missing:
        joined = ", ".join(str(path) for path in missing)
        raise FileNotFoundError(f"Missing fire-sorcerer raw source(s): {joined}")


def _sample_border_key(image: Image.Image) -> tuple[int, int, int]:
    """Match the imagegen chroma helper's deterministic border median."""
    rgba = image.convert("RGBA")
    pixels = rgba.load()
    width, height = rgba.size
    band = max(1, min(width, height, 6))
    step = max(1, min(width, height) // 256)
    samples: list[tuple[int, int, int]] = []

    for x in range(0, width, step):
        for y in range(band):
            samples.append(pixels[x, y][:3])
            samples.append(pixels[x, height - 1 - y][:3])
    for y in range(0, height, step):
        for x in range(band):
            samples.append(pixels[x, y][:3])
            samples.append(pixels[width - 1 - x, y][:3])

    if not samples:
        raise AssetContractError("Cannot sample a chroma key from an empty border")
    return (
        int(round(median(sample[0] for sample in samples))),
        int(round(median(sample[1] for sample in samples))),
        int(round(median(sample[2] for sample in samples))),
    )


def _remove_green_screen(image: Image.Image) -> tuple[Image.Image, tuple[int, int, int]]:
    """Remove the accepted flat green background with binary alpha.

    The sampled key and tolerance reproduce the already-reviewed alpha sources,
    while keeping this production pipeline independent from ``tmp``.
    """
    rgba = np.array(image.convert("RGBA"), dtype=np.uint8)
    key = _sample_border_key(image)
    distance = np.max(
        np.abs(
            rgba[:, :, :3].astype(np.int16)
            - np.asarray(key, dtype=np.int16)
        ),
        axis=2,
    )
    visible = (rgba[:, :, 3] > 0) & (distance > CHROMA_TOLERANCE)
    rgba[visible, 3] = 255
    rgba[~visible] = (0, 0, 0, 0)
    return Image.fromarray(rgba), key


def _crop_grid_cell(
    sheet: Image.Image,
    row: int,
    column: int,
) -> Image.Image:
    left = round(column * sheet.width / float(GRID_COLUMNS))
    right = round((column + 1) * sheet.width / float(GRID_COLUMNS))
    top = round(row * sheet.height / float(GRID_ROWS))
    bottom = round((row + 1) * sheet.height / float(GRID_ROWS))
    return sheet.crop((left, top, right, bottom))


def _validate_source_frame(
    image: Image.Image,
    label: str,
    *,
    allow_empty: bool = False,
) -> dict | None:
    """Run the mandatory analyzer call and enforce its hard gate."""
    bbox = image.getchannel("A").getbbox()
    if bbox is None:
        if allow_empty:
            print(f"SOURCE_FRAME_OK {label} empty=true")
            return None
        raise AssetContractError(f"{label}: source frame is empty")

    analysis = analyze_image(image)
    confidence = float(analysis["confidence"])
    logical_width = int(analysis["subject_grid_width"])
    logical_height = int(analysis["subject_grid_height"])
    if confidence < MIN_GRID_CONFIDENCE:
        raise AssetContractError(
            f"{label}: grid confidence {confidence:.3f} is below "
            f"{MIN_GRID_CONFIDENCE:.2f}; regenerate this frame instead of "
            "forcing compression"
        )
    if (
        logical_width > MAX_LOGICAL_SUBJECT_SIZE
        or logical_height > MAX_LOGICAL_SUBJECT_SIZE
    ):
        raise AssetContractError(
            f"{label}: logical subject {logical_width}x{logical_height} exceeds "
            f"{MAX_LOGICAL_SUBJECT_SIZE}x{MAX_LOGICAL_SUBJECT_SIZE}; regenerate "
            "this frame instead of forcing compression"
        )
    print(
        f"SOURCE_FRAME_OK {label} confidence={confidence:.3f} "
        f"logical={logical_width}x{logical_height} "
        f"grid={analysis['grid_cell_width']}x"
        f"{analysis['grid_cell_height']}"
    )
    return analysis


def _despill_logical_pixels(image: Image.Image) -> Image.Image:
    """Neutralize green-screen fringe without changing the alpha silhouette."""
    rgba = np.array(image.convert("RGBA"), dtype=np.uint8)
    alpha = rgba[:, :, 3] > 0
    red = rgba[:, :, 0].astype(np.int16)
    green = rgba[:, :, 1].astype(np.int16)
    blue = rgba[:, :, 2].astype(np.int16)
    fringe = alpha & (green > red + 18) & (green > blue + 18)
    neutral = np.maximum(red, blue)
    rgba[:, :, 1][fringe] = neutral[fringe].astype(np.uint8)
    rgba[:, :, 3][alpha] = 255
    rgba[~alpha] = (0, 0, 0, 0)
    return Image.fromarray(rgba)


def _sample_native_subject(image: Image.Image, analysis: dict) -> Image.Image:
    bbox_data = analysis["subject_bbox"]
    bbox = (
        int(bbox_data["left"]),
        int(bbox_data["top"]),
        int(bbox_data["right"]),
        int(bbox_data["bottom"]),
    )
    logical_size = (
        int(analysis["subject_grid_width"]),
        int(analysis["subject_grid_height"]),
    )
    subject = image.crop(bbox).resize(logical_size, Image.Resampling.NEAREST)
    return _despill_logical_pixels(subject)


def _place_character_subject(subject: Image.Image) -> Image.Image:
    frame = Image.new(
        "RGBA",
        (CHARACTER_FRAME_SIZE, CHARACTER_FRAME_SIZE),
        (0, 0, 0, 0),
    )
    left = round((CHARACTER_FRAME_SIZE - subject.width) * 0.5)
    top = CHARACTER_FOOT_BASELINE_Y - subject.height + 1
    if left < 0 or top < 0:
        raise AssetContractError(
            f"Character subject {subject.width}x{subject.height} does not fit "
            f"the fixed {CHARACTER_FRAME_SIZE}px frame and foot baseline"
        )
    frame.alpha_composite(subject, (left, top))
    return frame


def _place_fireball_subject(subject: Image.Image) -> Image.Image:
    frame = Image.new(
        "RGBA",
        (FIREBALL_FRAME_SIZE, FIREBALL_FRAME_SIZE),
        (0, 0, 0, 0),
    )
    left = round((FIREBALL_FRAME_SIZE - subject.width) * 0.5)
    top = round((FIREBALL_FRAME_SIZE - subject.height) * 0.5)
    if left < 0 or top < 0:
        raise AssetContractError(
            f"Fireball subject {subject.width}x{subject.height} does not fit "
            f"the {FIREBALL_FRAME_SIZE}px frame"
        )
    frame.alpha_composite(subject, (left, top))
    return frame


def _decoded_rgba_sha256(image: Image.Image) -> str:
    return hashlib.sha256(image.convert("RGBA").tobytes()).hexdigest()


def _horizontal_runs(mask_row: np.ndarray) -> list[tuple[int, int]]:
    runs: list[tuple[int, int]] = []
    run_start: int | None = None
    for x, visible in enumerate(mask_row):
        if bool(visible) and run_start is None:
            run_start = x
        elif not bool(visible) and run_start is not None:
            runs.append((run_start, x - 1))
            run_start = None
    if run_start is not None:
        runs.append((run_start, len(mask_row) - 1))
    return runs


def _connected_component_sizes(mask: np.ndarray) -> list[int]:
    """Return 4-neighbour alpha-component sizes for one native frame."""
    height, width = mask.shape
    visited = np.zeros_like(mask, dtype=bool)
    sizes: list[int] = []
    for y in range(height):
        for x in range(width):
            if not bool(mask[y, x]) or bool(visited[y, x]):
                continue
            stack = [(x, y)]
            visited[y, x] = True
            size = 0
            while stack:
                current_x, current_y = stack.pop()
                size += 1
                for next_x, next_y in (
                    (current_x - 1, current_y),
                    (current_x + 1, current_y),
                    (current_x, current_y - 1),
                    (current_x, current_y + 1),
                ):
                    if (
                        0 <= next_x < width
                        and 0 <= next_y < height
                        and bool(mask[next_y, next_x])
                        and not bool(visited[next_y, next_x])
                    ):
                        visited[next_y, next_x] = True
                        stack.append((next_x, next_y))
            sizes.append(size)
    return sorted(sizes, reverse=True)


def _longest_horizontal_run(
    mask_row: np.ndarray,
) -> tuple[int, int] | None:
    runs = _horizontal_runs(mask_row)
    if not runs:
        return None
    return max(runs, key=lambda run: run[1] - run[0] + 1)


def _audit_character_move_strip(move_strip: Image.Image) -> None:
    if move_strip.size != (
        CHARACTER_FRAME_SIZE * GRID_COLUMNS,
        CHARACTER_FRAME_SIZE,
    ):
        raise AssetContractError(
            f"Move strip is {move_strip.size}, expected 160x40"
        )
    _assert_binary_alpha(move_strip, "character move strip")
    rgba = np.array(move_strip.convert("RGBA"), dtype=np.uint8)
    transparent = rgba[:, :, 3] == 0
    if np.any(rgba[:, :, :3][transparent] != 0):
        raise AssetContractError(
            "Move strip transparent pixels must have zero RGB payload"
        )

    masks: list[np.ndarray] = []
    centroids: list[tuple[float, float]] = []
    foot_band_spans: list[int] = []
    ground_spans: list[int] = []
    bottom_run_counts: list[int] = []
    for frame_index in range(GRID_COLUMNS):
        frame_rgba = rgba[
            :,
            frame_index * CHARACTER_FRAME_SIZE:
                (frame_index + 1) * CHARACTER_FRAME_SIZE,
            :,
        ]
        mask = frame_rgba[:, :, 3] > 0
        visible_y, visible_x = np.nonzero(mask)
        if visible_x.size == 0:
            raise AssetContractError(
                f"Move frame {frame_index} is empty"
            )
        component_sizes = _connected_component_sizes(mask)
        if len(component_sizes) != 1:
            raise AssetContractError(
                f"Move frame {frame_index} is structurally disconnected: "
                f"components={component_sizes}"
            )
        bbox = (
            int(visible_x.min()),
            int(visible_y.min()),
            int(visible_x.max()) + 1,
            int(visible_y.max()) + 1,
        )
        if (
            bbox[0] < 1
            or bbox[1] < 1
            or bbox[2] > CHARACTER_FRAME_SIZE - 1
            or bbox[3] > CHARACTER_FRAME_SIZE - 1
        ):
            raise AssetContractError(
                f"Move frame {frame_index} lacks one-pixel cell padding: "
                f"{bbox}"
            )
        if bbox[3] - 1 != CHARACTER_FOOT_BASELINE_Y:
            raise AssetContractError(
                f"Move frame {frame_index} baseline is {bbox[3] - 1}, "
                f"expected {CHARACTER_FOOT_BASELINE_Y}"
            )
        bbox_center_x = (bbox[0] + bbox[2] - 1) * 0.5
        if abs(bbox_center_x - 19.5) > 1.0:
            raise AssetContractError(
                f"Move frame {frame_index} bbox center {bbox_center_x:.2f} "
                "drifted from the authored axis"
            )
        centroids.append(
            (float(visible_x.mean()), float(visible_y.mean()))
        )
        upper_waist_run = _longest_horizontal_run(
            mask[CHARACTER_WAIST_ROWS[0], :]
        )
        lower_waist_run = _longest_horizontal_run(
            mask[CHARACTER_WAIST_ROWS[1], :]
        )
        if upper_waist_run is None or lower_waist_run is None:
            raise AssetContractError(
                f"Move frame {frame_index} has an empty waist row"
            )
        upper_center = (upper_waist_run[0] + upper_waist_run[1]) * 0.5
        lower_center = (lower_waist_run[0] + lower_waist_run[1]) * 0.5
        waist_overlap = (
            min(upper_waist_run[1], lower_waist_run[1])
            - max(upper_waist_run[0], lower_waist_run[0])
            + 1
        )
        shorter_waist_width = min(
            upper_waist_run[1] - upper_waist_run[0] + 1,
            lower_waist_run[1] - lower_waist_run[0] + 1,
        )
        if (
            abs(upper_center - lower_center) > 1.0
            or waist_overlap < shorter_waist_width - 1
        ):
            raise AssetContractError(
                f"Move frame {frame_index} has a torn waist transition: "
                f"upper={upper_waist_run}, lower={lower_waist_run}, "
                f"overlap={waist_overlap}"
            )
        foot_y, foot_x = np.nonzero(
            mask[CHARACTER_FOOT_BASELINE_Y - 5:
                CHARACTER_FOOT_BASELINE_Y + 1, :]
        )
        if foot_x.size == 0:
            raise AssetContractError(
                f"Move frame {frame_index} has no readable foot band"
            )
        foot_band_spans.append(int(foot_x.max() - foot_x.min() + 1))
        bottom_runs = _horizontal_runs(
            mask[CHARACTER_FOOT_BASELINE_Y, :]
        )
        bottom_run_counts.append(len(bottom_runs))
        ground_spans.append(
            bottom_runs[-1][1] - bottom_runs[0][0] + 1
        )
        masks.append(mask)

    centroid_x_span = max(value[0] for value in centroids) - min(
        value[0] for value in centroids
    )
    centroid_y_span = max(value[1] for value in centroids) - min(
        value[1] for value in centroids
    )
    if centroid_x_span > 1.5 or centroid_y_span > 1.5:
        raise AssetContractError(
            "Move animation center drift exceeds the reviewed limit: "
            f"x={centroid_x_span:.3f}, y={centroid_y_span:.3f}"
        )
    contact_spans = (ground_spans[0], ground_spans[2])
    passing_spans = (ground_spans[1], ground_spans[3])
    if min(contact_spans) < max(passing_spans) + 3:
        raise AssetContractError(
            "Contact poses must keep a wider grounded stance than passing "
            "poses: "
            f"contact={contact_spans}, passing={passing_spans}"
        )
    if (
        bottom_run_counts[0] < 2
        or bottom_run_counts[2] < 2
        or bottom_run_counts[1] != 1
        or bottom_run_counts[3] != 1
    ):
        raise AssetContractError(
            "Move gait must keep two grounded boots in contact poses and "
            "one grounded boot in passing poses: "
            f"runs={bottom_run_counts}"
        )
    for first, second, label in (
        (0, 2, "contact"),
        (1, 3, "passing"),
    ):
        xor_pixels = int(np.logical_xor(
            masks[first],
            masks[second],
        ).sum())
        intersection = int(np.logical_and(
            masks[first],
            masks[second],
        ).sum())
        union = int(np.logical_or(
            masks[first],
            masks[second],
        ).sum())
        iou = float(intersection) / float(max(union, 1))
        if xor_pixels < 32 or iou < 0.60:
            raise AssetContractError(
                f"Opposite {label} poses are not a coherent leg swap: "
                f"xor={xor_pixels}, iou={iou:.3f}"
            )

    rgba_sha256 = _decoded_rgba_sha256(move_strip)
    if rgba_sha256 != CHARACTER_MOVE_RGBA_SHA256:
        raise AssetContractError(
            "Move strip RGBA fingerprint changed without visual approval: "
            f"{rgba_sha256}"
        )
    print(
        "MOVE_STRIP_OK "
        f"centroid_x_span={centroid_x_span:.3f} "
        f"centroid_y_span={centroid_y_span:.3f} "
        f"foot_band_spans={foot_band_spans} "
        f"ground_spans={ground_spans} "
        f"bottom_runs={bottom_run_counts} "
        f"rgba_sha256={rgba_sha256}"
    )


def _build_character_sheet(
    source: Image.Image,
    replacement: Image.Image,
    move_strip: Image.Image,
) -> Image.Image:
    sheet = Image.new(
        "RGBA",
        (
            CHARACTER_FRAME_SIZE * GRID_COLUMNS,
            CHARACTER_FRAME_SIZE * GRID_ROWS,
        ),
        (0, 0, 0, 0),
    )
    replacement_analysis = _validate_source_frame(
        replacement,
        "character replacement r2c1",
    )
    assert replacement_analysis is not None

    for row in range(GRID_ROWS):
        for column in range(GRID_COLUMNS):
            if row == 0:
                continue
            label = f"character r{row}c{column}"
            if (row, column) == CHARACTER_REPLACEMENT_CELL:
                cell = replacement
                analysis = replacement_analysis
                label += " <- replacement"
            else:
                cell = _crop_grid_cell(source, row, column)
                analysis = _validate_source_frame(
                    cell,
                    label,
                    allow_empty=(row, column)
                    == OPTIONAL_EMPTY_CHARACTER_CELL,
                )
            if analysis is None:
                continue
            subject = _sample_native_subject(cell, analysis)
            frame = _place_character_subject(subject)
            sheet.alpha_composite(
                frame,
                (
                    column * CHARACTER_FRAME_SIZE,
                    row * CHARACTER_FRAME_SIZE,
                ),
            )
    static_rows = sheet.crop(
        (
            0,
            CHARACTER_FRAME_SIZE,
            CHARACTER_FRAME_SIZE * GRID_COLUMNS,
            CHARACTER_FRAME_SIZE * GRID_ROWS,
        )
    )
    static_rows_sha256 = _decoded_rgba_sha256(static_rows)
    if static_rows_sha256 != STATIC_CHARACTER_ROWS_RGBA_SHA256:
        raise AssetContractError(
            "Windup/attack/death rows changed while rebuilding move: "
            f"{static_rows_sha256}"
        )
    _audit_character_move_strip(move_strip)
    static_rows_before = static_rows.tobytes()
    sheet.paste(move_strip, (0, 0))
    if sheet.crop((0, 0, 160, 40)).tobytes() != move_strip.tobytes():
        raise AssetContractError("Move row replacement was not pixel exact")
    if (
        sheet.crop((0, 40, 160, 160)).tobytes()
        != static_rows_before
    ):
        raise AssetContractError(
            "Move row replacement mutated a non-move animation row"
        )
    return sheet


def _build_fireball_sheet(source: Image.Image) -> Image.Image:
    sheet = Image.new(
        "RGBA",
        (
            FIREBALL_FRAME_SIZE * GRID_COLUMNS,
            FIREBALL_FRAME_SIZE * GRID_ROWS,
        ),
        (0, 0, 0, 0),
    )
    for row in range(GRID_ROWS):
        for column in range(GRID_COLUMNS):
            label = f"fireball r{row}c{column}"
            cell = _crop_grid_cell(source, row, column)
            analysis = _validate_source_frame(
                cell,
                label,
                allow_empty=(row, column) == OPTIONAL_EMPTY_FIREBALL_CELL,
            )
            if analysis is None:
                continue
            subject = _sample_native_subject(cell, analysis)
            frame = _place_fireball_subject(subject)
            sheet.alpha_composite(
                frame,
                (
                    column * FIREBALL_FRAME_SIZE,
                    row * FIREBALL_FRAME_SIZE,
                ),
            )
    return sheet


def _animation_entry(
    name: str,
    speed: float,
    loop: bool,
    frame_count: int,
) -> str:
    frames = [
        "{\n"
        '"duration": 1.0,\n'
        f'"texture": SubResource("AtlasTexture_{name}_{column}")\n'
        "}"
        for column in range(frame_count)
    ]
    return (
        "{\n"
        f'"frames": [{", ".join(frames)}],\n'
        f'"loop": {str(loop).lower()},\n'
        f'"name": &"{name}",\n'
        f'"speed": {speed:.1f}\n'
        "}"
    )


def _write_sprite_frames(
    output_path: Path,
    texture_path: str,
    frame_size: int,
    animations: OrderedDict[str, tuple[int, float, bool]],
    resource_uid: str,
    texture_uid: str,
    move_texture_path: str | None = None,
) -> None:
    if frame_size > MAX_LOGICAL_SUBJECT_SIZE:
        raise AssetContractError(
            f"Atlas frame {frame_size}x{frame_size} exceeds the 40px contract"
        )
    lines = [
        (
            '[gd_resource type="SpriteFrames" format=3 '
            f'uid="{resource_uid}"]'
        ),
        "",
        (
            f'[ext_resource type="Texture2D" uid="{texture_uid}" '
            f'path="{texture_path}" id="1_texture"]'
        ),
        "",
    ]
    if move_texture_path is not None:
        lines.extend(
            [
                (
                    '[ext_resource type="Texture2D" '
                    f'path="{move_texture_path}" id="2_move"]'
                ),
                "",
            ]
        )
    animation_names = sorted(animations)
    for name in animation_names:
        row, _speed, _loop = animations[name]
        uses_move_strip = name == "move" and move_texture_path is not None
        frame_count = MOVE_FRAME_COUNT if uses_move_strip else GRID_COLUMNS
        texture_id = "2_move" if uses_move_strip else "1_texture"
        for column in range(frame_count):
            lines.extend(
                [
                    (
                        '[sub_resource type="AtlasTexture" '
                        f'id="AtlasTexture_{name}_{column}"]'
                    ),
                    f'atlas = ExtResource("{texture_id}")',
                    (
                        f"region = Rect2({column * frame_size}, "
                        f"{0 if uses_move_strip else row * frame_size}, "
                        f"{frame_size}, {frame_size})"
                    ),
                    "filter_clip = true",
                    "",
                ]
            )
    entries = [
        _animation_entry(
            name,
            animations[name][1],
            animations[name][2],
            (
                MOVE_FRAME_COUNT
                if name == "move" and move_texture_path is not None
                else GRID_COLUMNS
            ),
        )
        for name in animation_names
    ]
    lines.extend(
        [
            "[resource]",
            f"animations = [{', '.join(entries)}]",
            "",
        ]
    )
    output_path.write_text(
        "\n".join(lines),
        encoding="utf-8",
        newline="\n",
    )


def _assert_binary_alpha(image: Image.Image, label: str) -> None:
    alpha_values = set(image.convert("RGBA").getchannel("A").getdata())
    if not alpha_values.issubset({0, 255}):
        raise AssetContractError(
            f"{label}: output alpha is not binary: {sorted(alpha_values)}"
        )


def _save_if_decoded_changed(image: Image.Image, path: Path) -> None:
    if path.is_file():
        existing = Image.open(path).convert("RGBA")
        if existing.size == image.size and existing.tobytes() == image.tobytes():
            return
    image.save(path, optimize=True)


def _audit_character_output(sheet: Image.Image) -> None:
    expected_size = (
        CHARACTER_FRAME_SIZE * GRID_COLUMNS,
        CHARACTER_FRAME_SIZE * GRID_ROWS,
    )
    if sheet.size != expected_size:
        raise AssetContractError(
            f"Character sheet is {sheet.size}, expected {expected_size}"
        )
    _assert_binary_alpha(sheet, "character sheet")
    for row in range(GRID_ROWS):
        for column in range(GRID_COLUMNS):
            frame = sheet.crop(
                (
                    column * CHARACTER_FRAME_SIZE,
                    row * CHARACTER_FRAME_SIZE,
                    (column + 1) * CHARACTER_FRAME_SIZE,
                    (row + 1) * CHARACTER_FRAME_SIZE,
                )
            )
            bbox = frame.getchannel("A").getbbox()
            if bbox is None:
                if (row, column) == OPTIONAL_EMPTY_CHARACTER_CELL:
                    continue
                raise AssetContractError(
                    f"Character output r{row}c{column} is unexpectedly empty"
                )
            if bbox[2] > CHARACTER_FRAME_SIZE or bbox[3] > CHARACTER_FRAME_SIZE:
                raise AssetContractError(
                    f"Character output r{row}c{column} exceeds its frame"
                )
            if bbox[3] - 1 != CHARACTER_FOOT_BASELINE_Y:
                raise AssetContractError(
                    f"Character output r{row}c{column} baseline is "
                    f"{bbox[3] - 1}, expected {CHARACTER_FOOT_BASELINE_Y}"
                )


def _audit_fireball_output(sheet: Image.Image) -> None:
    expected_size = (
        FIREBALL_FRAME_SIZE * GRID_COLUMNS,
        FIREBALL_FRAME_SIZE * GRID_ROWS,
    )
    if sheet.size != expected_size:
        raise AssetContractError(
            f"Fireball sheet is {sheet.size}, expected {expected_size}"
        )
    _assert_binary_alpha(sheet, "fireball sheet")
    for row in range(GRID_ROWS):
        for column in range(GRID_COLUMNS):
            frame = sheet.crop(
                (
                    column * FIREBALL_FRAME_SIZE,
                    row * FIREBALL_FRAME_SIZE,
                    (column + 1) * FIREBALL_FRAME_SIZE,
                    (row + 1) * FIREBALL_FRAME_SIZE,
                )
            )
            bbox = frame.getchannel("A").getbbox()
            if bbox is None and (row, column) != OPTIONAL_EMPTY_FIREBALL_CELL:
                raise AssetContractError(
                    f"Fireball output r{row}c{column} is unexpectedly empty"
                )
            if bbox is not None and (
                bbox[2] > FIREBALL_FRAME_SIZE
                or bbox[3] > FIREBALL_FRAME_SIZE
            ):
                raise AssetContractError(
                    f"Fireball output r{row}c{column} exceeds its frame"
                )


def main() -> None:
    _require_sources()
    TEXTURE_DIR.mkdir(parents=True, exist_ok=True)
    ANIMATION_DIR.mkdir(parents=True, exist_ok=True)

    character_source, character_key = _remove_green_screen(
        Image.open(CHARACTER_SOURCE)
    )
    replacement_source, replacement_key = _remove_green_screen(
        Image.open(CHARACTER_REPLACEMENT_SOURCE)
    )
    move_strip_source = Image.open(
        CHARACTER_MOVE_NATIVE_SOURCE
    ).convert("RGBA")
    fireball_source, fireball_key = _remove_green_screen(
        Image.open(FIREBALL_SOURCE)
    )
    print(
        "CHROMA_KEYS "
        f"character=#{character_key[0]:02x}{character_key[1]:02x}"
        f"{character_key[2]:02x} "
        f"replacement=#{replacement_key[0]:02x}{replacement_key[1]:02x}"
        f"{replacement_key[2]:02x} "
        f"fireball=#{fireball_key[0]:02x}{fireball_key[1]:02x}"
        f"{fireball_key[2]:02x} tolerance={CHROMA_TOLERANCE}"
    )

    character_sheet = _build_character_sheet(
        character_source,
        replacement_source,
        move_strip_source,
    )
    move_strip = _build_move_strip(
        CHARACTER_MOVE_SOURCE,
        character_sheet,
        "fire sorcerer move",
        target_heights=CHARACTER_MOVE_TARGET_HEIGHTS,
    )
    _assert_move_strip_contract(move_strip, "fire sorcerer move")
    move_hash = _decoded_rgba_sha256(move_strip)
    if move_hash != CHARACTER_MOVE_8POSE_RGBA_SHA256:
        raise AssetContractError(
            "Eight-pose move strip fingerprint changed without approval: "
            f"{move_hash}"
        )
    fireball_sheet = _build_fireball_sheet(fireball_source)
    _audit_character_output(character_sheet)
    _audit_fireball_output(fireball_sheet)

    _save_if_decoded_changed(character_sheet, CHARACTER_OUTPUT)
    _save_if_decoded_changed(move_strip, CHARACTER_MOVE_OUTPUT)
    _save_if_decoded_changed(fireball_sheet, FIREBALL_OUTPUT)
    _write_sprite_frames(
        CHARACTER_ANIMATION_OUTPUT,
        "res://resources/texture/fire_sorcerer.png",
        CHARACTER_FRAME_SIZE,
        CHARACTER_ANIMATIONS,
        CHARACTER_ANIMATION_UID,
        CHARACTER_TEXTURE_UID,
        "res://resources/texture/fire_sorcerer_move.png",
    )
    _write_sprite_frames(
        FIREBALL_ANIMATION_OUTPUT,
        "res://resources/texture/fire_sorcerer_fireball.png",
        FIREBALL_FRAME_SIZE,
        FIREBALL_ANIMATIONS,
        FIREBALL_ANIMATION_UID,
        FIREBALL_TEXTURE_UID,
    )

    print(
        "FIRE_SORCERER_ASSETS_OK "
        f"character={character_sheet.width}x{character_sheet.height} "
        f"frame={CHARACTER_FRAME_SIZE}x{CHARACTER_FRAME_SIZE} "
        f"foot_baseline={CHARACTER_FOOT_BASELINE_Y} "
        f"move={move_strip.width}x{move_strip.height} "
        f"move_rgba_sha256={CHARACTER_MOVE_8POSE_RGBA_SHA256} "
        f"fireball={fireball_sheet.width}x{fireball_sheet.height} "
        f"fireball_frame={FIREBALL_FRAME_SIZE}x{FIREBALL_FRAME_SIZE} "
        "alpha=binary sampling=nearest unsafe_compression=false"
    )


if __name__ == "__main__":
    main()
